### ISSUE TITLE
Feature idea: Gradually change color temperature according to daytime

### ISSUE THREAD

**Issue by sicherist** [Fuchs/hoppla-sa#13]
Thank you very much for creating this plasmoid! I love it for setting color temperature of my hue lights and switching them on and off.

Do you think it would be possible to add a feature, that would allow the lamps to automatically, gradually fade from cool-white in the afternoon to warm-white in the evening?

For example by reading the current display color temperature from the plasmoid "redshift-control" (https://phabricator.kde.org/source/plasma-redshift-control/) and set the color temperature of the hue lights accordingly?

**Comment by Fuchs** [comment]
Hi, technically and in general yes, you have two possibilities, and I honestly prefer the latter. 
You could either make sure that the computer with the plasmoid is running. It would then have to read out the daytime from something that does offer an interface for that. I assume the system clock does, the redshift plasmoid probably not so, but redshift itself. However, that would require the computer to be running. 

The imho better idea is to do this via timers. You can already configure such timers and actions with my plasmoid, and they store the actions on the bridge, so no computer has to be running. Maybe I could create a nice UI shortcut for it, but in general it should already be possible.

**Comment by sicherist** [comment]
I wasn't even aware of the extensive schedule-menu hidden in the hoppla-sa settings :) Great work! One thing II think could be useful in the schedule-settings is a day / night setting. In the hue bridge there is a boolean value "daylight" (.../sensors/1/) that depending on the users location and date determines if it is day or night.  So could make a schedule for example if daylight is true - set color-temperature to 5000 K; if daylight is false set color temperature to 3000 K.

**Comment by Fuchs** [comment]
Hi, 

as far as I am aware this does require a sensor, I'm afraid I do not have one, so it's something that I can't really test. However, pull requests more than welcome from people who have one and can test :)

**Comment by sicherist** [comment]
Programmieren kann ich leider nicht - nur kurz der Vollständigkeit
halber: Einen Sensor braucht man dafür nicht. Es handelt sich um einen
"virtuellen" Sensor innerhalb der Hue Bridge. Aus dem Längen- und
Breitengrad sowie dem aktuellem Datum wird der Zeitpunkt der Dämmerung
berechnet und dann je nach Uhrzeit wird "daylight" true bzw. false
ausgegeben.

Viele Grüße!
