### ISSUE TITLE
Group icon/title jumps about

### ISSUE THREAD

**Issue by muesli** [Fuchs/hoppla-sa#15]
When expanding a group, the vertically centered group's icon and text slightly jump up by a couple of pixels. Collapsing the group does not reset the state.

Example after having expanded/recollapsed the groups:
![image](https://user-images.githubusercontent.com/146378/69774006-e26f5300-1194-11ea-830e-7df245b5e785.png)

**Comment by Fuchs** [comment]
Yeah, I did notice that with some Qt / QML versions, I think the bug might be somewhere there and not in the actual plasmoid, because I wasn't able to reliably fix it. 
If somebody with a better understanding of QML has a fix, pull requests very welcome.

**Comment by Fuchs** [comment]
Nevermind, please check if the above commit fixes this for you, the anchor changes in GroupItem and LightItem is what you are looking for, the other change should not hurt either though. 

I assume this could break for odd icon sizes, but then it should break the icon, too  (see #14)

**Comment by muesli** [comment]
On the upside, I can confirm that they're not jumping about anymore. Sadly they're now always stuck in the slightly off-center position, closer to the horizontal divider (as in screenshot).

**Comment by Fuchs** [comment]
Odd, for me it is quite centered on all three boxes, and code-wise I think it should be. 
You can give it a slighter bigger margin (use the units provided) and see what centers it for you, then I can have a look on what it looks like on my boxes.
