### ISSUE TITLE
Error loading QML file

### ISSUE THREAD

**Issue by drdang2** [Fuchs/hoppla-sa#23]
Currently on Kubuntu 20.04, Plasma 5.18.5....    I installed this plugin via Discover app store and receive this error when I place the widget on my desktop

Error loading QML file: file:///home/ecov/.local/share/plasma/plasmoids/ch.fuchsnet.plasma.hoppla-sa/contents/ui/main.qml:20:1: module "QtQml" version 2.15 is not installed

Probably an easy fix but not sure what to do. 

"apt-cache search qtml" shows a couple available packages: 
python3-pyside2.qtqml       
qml-module-qtqml-models2    
qml-module-qtqml-statemachine

Do i need to install one of these? 

Thank you

Edit: whoops, just noticed you require plasma 5.21

**Comment by Fuchs** [comment]
Hi, plasma 5.21 is only needed in the most recent version (4.*), if you have an older version of plasma, the most recent 3.* version should do. I think it is still available via the plugin store, if not, you can fetch it from https://github.com/Fuchs/hoppla-sa/releases

Hope that helps!
