### ISSUE TITLE
ID in "Edit command" is not set for Group "all" 

### ISSUE THREAD

**Issue by Ch3wi3** [Fuchs/hoppla-sa#3]
If I edit a command in an custom "action" the property ID is not set correctly when group is "0: All lights" 
If I choose any other group the ID is set correctly. 

Steps to reproduce: 

- create an new action
- add new command to it
- change "Target" of the new command to "Groups" and select Group "0: All lights" 
- save 

--> ID field of the Command is empty

- change the group of the new command to any other Group with an ID != 0 

--> ID field is set correctly to the group ID

**Comment by Fuchs** [comment]
Yep, that is a bug I introduced in a change recently, will be fixed in the next release. 
If you want a fix in the meantime: 

Change Line 427 of ActionEditor.qml to 
        targetModel.append( { text: "0: " + i18n("All lights"), value: "0", uuid: "0"} );
save and restart plasma. 

Thanks for the report :)
