### ISSUE TITLE
Uninstall command fails

### ISSUE THREAD

**Issue by muesli** [Fuchs/hoppla-sa#4]
ArchLinux, latest Plasma:

The uninstall command for a local installation fails here. What did work instead was:

```
cd package
plasmapkg2 -r .
```

**Comment by Fuchs** [comment]
Hi, 
I'm afraid I have zero experience with CMAKE, so I shall look into it next week at Randa with some people who do, probably that's easy to add / fix. If anyone already knows, pull requests with fix welcome.

**Comment by muesli** [comment]
@Fuchs: I'm actually referring to the "plasmapkg -r" call you mention in the README.

**Comment by Fuchs** [comment]
Would probably be nicer to have it in the make, but sure, I can adapt the README, probably it just needs the path, shall test at home, as this would be prettier than cd

**Comment by Fuchs** [comment]
Fixed in the latest commit for now, will see if I want to do a cmake thingie later, focus now is on accessibility. Thanks for the report.
